{
 "title": "Crypto Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Баланс", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Текущий баланс",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wallet_balance", "legendFormat": "{{exported_job}} {{currency}}" }
   ]
  },
  {
   "title": "Баланс",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 12, "y": 1 },
   "targets": [
    { "expr": "wallet_balance", "legendFormat": "{{exported_job}} {{currency}}" }
   ]
  },
  {
   "title": "Время в пути данных от сервера биржи до принятия",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "Медиана времени в мс",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    { "expr": "recieve_from_server_duration", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "Время в мс",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 12, "y": 16 },
   "targets": [
    { "expr": "recieve_from_server_duration", "legendFormat": "{{exported_job}}" }
   ]
  },
  { "title": "Выполнение цикла трейдинга", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Медиана времени в мс",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    { "expr": "orders_duration", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "Время в мс",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 12, "y": 31 },
   "targets": [
    { "expr": "orders_duration", "legendFormat": "{{exported_job}}" }
   ]
  },
  { "title": "Выполнение анализа", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Медиана времени в мкс",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "median" ] } },
   "targets": [
    { "expr": "analyze_duration", "legendFormat": "{{exported_job}}" }
   ]
  },
  {
   "title": "Время в мкс",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 12, "y": 46 },
   "targets": [
    { "expr": "analyze_duration", "legendFormat": "{{exported_job}}" }
   ]
  }
 ]
}