package config

import "os"


var (
	API_KEY string = os.Getenv("API_KEY")
	API_KEY_SECRET string = os.Getenv("API_KEY_SECRET")
)

type Pair struct {
	First  string
	Second string
}

var (
	SUBSCRIBE_TICKERS_LIST = map[string]Pair{
		"BTCBRZ": {"BTC", "BRZ"},
		"USDTBRZ": {"USDT", "BRZ"},
		"BTCDAI": {"BTC", "DAI"},
		"ETHDAI": {"ETH", "DAI"},
		"DAIUSDT": {"DAI", "USDT"},
		"METHETH": {"METH", "ETH"},
		"METHUSDT": {"METH", "USDT"},
		"ETHBTC": {"ETH", "BTC"},
		"SOLBTC": {"SOL", "BTC"},
		"WBTCBTC": {"WBTC", "BTC"},
		"WBTCUSDT": {"WBTC", "USDT"},
		"XRPUSDT": {"XRP", "USDT"},
		"XRPBTC": {"XRP", "BTC"},
		"XRPUSDC": {"XRP", "USDC"},
		"XRPEUR": {"XRP", "EUR"},
		"LTCBTC": {"LTC", "BTC"},
		"LTCUSDT": {"LTC", "USDT"},
		"LTCUSDC": {"LTC", "USDC"},
		"LTCEUR": {"LTC", "EUR"},
		"DOTUSDT": {"DOT", "USDT"},
		"DOTUSDC": {"DOT", "USDC"},
		"DOTBTC": {"DOT", "BTC"},
		"XLMUSDT": {"XLM", "USDT"},
		"XLMUSDC": {"XLM", "USDC"},
		"XLMBTC": {"XLM", "BTC"},
		"MNTUSDT": {"MNT", "USDT"},
		"MNTUSDC": {"MNT", "USDC"},
		"MNTBTC": {"MNT", "BTC"},
		"ALGOUSDT": {"ALGO", "USDT"},
		"ALGOBTC": {"ALGO", "BTC"},
		"MANAUSDT": {"MANA", "USDT"},
		"MANAUSDC": {"MANA", "USDC"},
		"MANABTC": {"MANA", "BTC"},
		"SANDUSDT": {"SAND", "USDT"},
		"SANDUSDC": {"SAND", "USDC"},
		"SANDBTC": {"SAND", "BTC"},
		"BBSOLUSDT": {"BBSOL", "USDT"},
		"BBSOLUSDC": {"BBSOL", "USDC"},
		"BBSOLSOL": {"BBSOL", "SOL"},
		"USDTTRY": {"USDT", "TRY"},
		"BTCTRY": {"BTC", "TRY"},
		"ETHTRY": {"ETH", "TRY"},
		"USDTPLN": {"USDT", "PLN"},
		"BTCPLN": {"BTC", "PLN"},
		"ETHPLN": {"ETH", "PLN"},
		"USDTBRL": {"USDT", "BRL"},
		"BTCBRL": {"BTC", "BRL"},
		"ETHBRL": {"ETH", "BRL"},
		"USDCBRL": {"USDC", "BRL"},
		"SOLBRL": {"SOL", "BRL"},
		"USDTEUR": {"USDT", "EUR"},
		"USDCEUR": {"USDC", "EUR"},
		"BTCEUR": {"BTC", "EUR"},
		"ETHEUR": {"ETH", "EUR"},
		"SOLEUR": {"SOL", "EUR"},
		"DOGEEUR": {"DOGE", "EUR"},
		"DOGEUSDC": {"DOGE", "USDC"},
		"DOGEUSDT": {"DOGE", "USDT"},
		"PEPEEUR": {"PEPE", "EUR"},
		"PEPEUSDC": {"PEPE", "USDC"},
		"PEPEUSDT": {"PEPE", "USDT"},
		"ADAEUR": {"ADA", "EUR"},
		"ADAUSDC": {"ADA", "USDC"},
		"ADAUSDT": {"ADA", "USDT"},
		"WIFEUR": {"WIF", "EUR"},
		"WIFUSDC": {"WIF", "USDC"},
		"WIFUSDT": {"WIF", "USDT"},
		"ENAEUR": {"ENA", "EUR"},
		"ENAUSDT": {"ENA", "USDT"},
		"SHIBEUR": {"SHIB", "EUR"},
		"SHIBUSDC": {"SHIB", "USDC"},
		"SHIBUSDT": {"SHIB", "USDT"},
		"WLDEUR": {"WLD", "EUR"},
		"WLDUSDC": {"WLD", "USDC"},
		"WLDUSDT": {"WLD", "USDT"},
		"NEAREUR": {"NEAR", "EUR"},
		"NEARUSDC": {"NEAR", "USDC"},
		"NEARUSDT": {"NEAR", "USDT"},
		"LINKEUR": {"LINK", "EUR"},
		"LINKUSDC": {"LINK", "USDC"},
		"LINKUSDT": {"LINK", "USDT"},
		"ONDOEUR": {"ONDO", "EUR"},
		"ONDOUSDC": {"ONDO", "USDC"},
		"ONDOUSDT": {"ONDO", "USDT"},
		"TONEUR": {"TON", "EUR"},
		"TONUSDC": {"TON", "USDC"},
		"TONUSDT": {"TON", "USDT"},
		"AVAXEUR": {"AVAX", "EUR"},
		"AVAXUSDC": {"AVAX", "USDC"},
		"AVAXUSDT": {"AVAX", "USDT"},
		"CATIEUR": {"CATI", "EUR"},
		"CATIUSDC": {"CATI", "USDC"},
		"CATIUSDT": {"CATI", "USDT"},
		"DOGSEUR": {"DOGS", "EUR"},
		"DOGSUSDC": {"DOGS", "USDC"},
		"DOGSUSDT": {"DOGS", "USDT"},
		"STETHEUR": {"STETH", "EUR"},
		"STETHUSDT": {"STETH", "USDT"},
		"USDEUSDT": {"USDE", "USDT"},
		"USDEUSDC": {"USDE", "USDC"},
		"SOLUSDE": {"SOL", "USDE"},
		"ETHUSDE": {"ETH", "USDE"},
		"BTCUSDE": {"BTC", "USDE"},
		"SUIUSDT": {"SUI", "USDT"},
		"SUIUSDC": {"SUI", "USDC"},
		"ETHUSDC": {"ETH", "USDC"},
		"BTCUSDC": {"BTC", "USDC"},
		"SOLUSDC": {"SOL", "USDC"},
		"BNBUSDC": {"BNB", "USDC"},
		"BNBUSDT": {"BNB", "USDT"},
		"ARBUSDC": {"ARB", "USDC"},
		"ARBUSDT": {"ARB", "USDT"},
		"OPUSDC": {"OP", "USDC"},
		"OPUSDT": {"OP", "USDT"},
		"APTUSDC": {"APT", "USDC"},
		"APTUSDT": {"APT", "USDT"},
		"TRUMPUSDC": {"TRUMP", "USDC"},
		"TRUMPUSDT": {"TRUMP", "USDT"},
		"TRXUSDC": {"TRX", "USDC"},
		"TRXUSDT": {"TRX", "USDT"},
		"STRKUSDC": {"STRK", "USDC"},
		"STRKUSDT": {"STRK", "USDT"},
		"SWELLUSDC": {"SWELL", "USDC"},
		"SWELLUSDT": {"SWELL", "USDT"},
		"ZROUSDC": {"ZRO", "USDC"},
		"ZROUSDT": {"ZRO", "USDT"},
		"LDOUSDC": {"LDO", "USDC"},
		"LDOUSDT": {"LDO", "USDT"},
		"CHZUSDC": {"CHZ", "USDC"},
		"CHZUSDT": {"CHZ", "USDT"},
		"ATOMUSDC": {"ATOM", "USDC"},
		"ATOMUSDT": {"ATOM", "USDT"},
		"KASUSDC": {"KAS", "USDC"},
		"KASUSDT": {"KAS", "USDT"},
		"TIAUSDC": {"TIA", "USDC"},
		"TIAUSDT": {"TIA", "USDT"},
		"LUNCUSDC": {"LUNC", "USDC"},
		"LUNCUSDT": {"LUNC", "USDT"},
		"FETUSDC": {"FET", "USDC"},
		"FETUSDT": {"FET", "USDT"},
		"FILUSDC": {"FIL", "USDC"},
		"FILUSDT": {"FIL", "USDT"},
		"BONKUSDC": {"BONK", "USDC"},
		"BONKUSDT": {"BONK", "USDT"},
		"ZKUSDC": {"ZK", "USDC"},
		"ZKUSDT": {"ZK", "USDT"},
		"SEIUSDC": {"SEI", "USDC"},
		"SEIUSDT": {"SEI", "USDT"},
		"APEUSDC": {"APE", "USDC"},
		"APEUSDT": {"APE", "USDT"},
		"MEWUSDC": {"MEW", "USDC"},
		"MEWUSDT": {"MEW", "USDT"},
		"INJUSDC": {"INJ", "USDC"},
		"INJUSDT": {"INJ", "USDT"},
		"UNIUSDC": {"UNI", "USDC"},
		"UNIUSDT": {"UNI", "USDT"},
		"EOSUSDC": {"EOS", "USDC"},
		"EOSUSDT": {"EOS", "USDT"},
		"BRETTUSDC": {"BRETT", "USDC"},
		"BRETTUSDT": {"BRETT", "USDT"},
		"ICPUSDC": {"ICP", "USDC"},
		"ICPUSDT": {"ICP", "USDT"},
		"HFTUSDC": {"HFT", "USDC"},
		"HFTUSDT": {"HFT", "USDT"},
		"BCHUSDC": {"BCH", "USDC"},
		"BCHUSDT": {"BCH", "USDT"},
		"JASMYUSDC": {"JASMY", "USDC"},
		"JASMYUSDT": {"JASMY", "USDT"},
		"NOTUSDC": {"NOT", "USDC"},
		"NOTUSDT": {"NOT", "USDT"},
		"GMTUSDC": {"GMT", "USDC"},
		"GMTUSDT": {"GMT", "USDT"},
		"APEXUSDC": {"APEX", "USDC"},
		"APEXUSDT": {"APEX", "USDT"},
		"FLOKIUSDC": {"FLOKI", "USDC"},
		"FLOKIUSDT": {"FLOKI", "USDT"},
		"HMSTRUSDC": {"HMSTR", "USDC"},
		"HMSTRUSDT": {"HMSTR", "USDT"},
		"BTCUSDT": {"BTC", "USDT"},
		"ETHUSDT": {"ETH", "USDT"},
		"SOLUSDT": {"SOL", "USDT"},
		"USDCUSDT": {"USDC", "USDT"},
	}
	CURRENCIES_PRECISIONS = map[string]float64{
		"ADA": 0.00001,
		"ALGO": 0.0001,
		"APE": 0.01,
		"APEX": 0.01,
		"APT": 0.001,
		"ARB": 0.01,
		"ATOM": 0.01,
		"AVAX": 0.001,
		"BBSOL": 0.001,
		"BCH": 0.1,
		"BNB": 0.0001,
		"BRL": 0.000001,
		"BRZ": 0.00001,
		"BTC": 0.000000001,
		"CHZ": 0.01,
		"DAI": 0.00000001,
		"DOGE": 0.0001,
		"DOGS": 0.0001,
		"DOT": 0.001,
		"EOS": 0.01,
		"ETH": 0.0001,
		"EUR": 0.0000000001,
		"GMT": 0.0001,
		"JASMY": 0.02,
		"LDO": 0.0001,
		"LINK": 0.0001,
		"LTC": 0.00001,
		"LUNC": 0.01,
		"MANA": 0.01,
		"METH": 0.01,
		"MNT": 0.01,
		"NEAR": 0.001,
		"NOT": 0.000001,
		"OP": 0.01,
		"SAND": 0.0001,
		"SEI": 0.01,
		"SHIB": 0.00000000000000001,
		"SOL": 0.01,
		"STRK": 0.01,
		"SUI": 0.01,
		"TIA": 0.01,
		"TON": 0.01,
		"TRX": 0.00001,
		"TRY": 0.0000001,
		"UNI": 0.01,
		"USDC": 0.0000000001,
		"USDE": 0.00000001,
		"USDT": 0.0000000001,
		"WLD": 0.01,
		"XLM": 0.01,
		"XRP": 0.0001,
		"ZK": 0.01,
	  }
)
